# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCat58():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_cat58(self):
    self.driver.get("https://callback.58.com/antibot/verifycode?serialId=2d8fb2c57ecf192bfb4e547b60bbf921_ddc793b5ffbc404a97bb8f4d95692139&code=21&sign=07560e01a7b2db772d0acfb7e908641b&namespace=huangyelistpc&url=https%3A%2F%2Finfo5.58.com%2Fhezhou%2Fcat%2F%3Futm_source%3Dlink%26spm%3Du-Lj4SZGxa1luDubj.psy_jiugongge%26PGTID%3D0d100000-0293-562e-aa1d-a72ef06b6cd8%26ClickID%3D2")
    self.driver.set_window_size(887, 692)
    self.driver.find_element(By.ID, "btnSubmit").click()
    element = self.driver.find_element(By.ID, "btnSubmit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "dvc-captcha__canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "dvc-captcha__canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "dvc-captcha__canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "dvc-captcha__canvas").click()
    element = self.driver.find_element(By.LINK_TEXT, "狗")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "特惠九成新家具").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".board:nth-child(1) > a:nth-child(6)").click()
    self.vars["win4418"] = self.wait_for_window(2000)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.switch_to.window(self.vars["win4418"])
    self.vars["win9661"] = self.wait_for_window(2000)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.switch_to.window(self.vars["win5319"])
    self.vars["win617"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4418"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win9661"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win617"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win5319"])
  
